"""add escalation evidence and notification failure tracking to alerts

Revision ID: 10f9b6cf7932
Revises: 30b0e51a0e89
Create Date: 2026-07-19 07:47:11.245257

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "10f9b6cf7932"
down_revision: Union[str, Sequence[str], None] = "30b0e51a0e89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alerts", sa.Column("escalation_evidence_statistic", sa.Float(), nullable=True))
    op.add_column("alerts", sa.Column("escalation_evidence_threshold", sa.Float(), nullable=True))
    op.add_column(
        "alerts", sa.Column("escalation_evidence_baseline_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "alerts", sa.Column("escalation_evidence_config_hash", sa.String(), nullable=True)
    )
    op.add_column("alerts", sa.Column("escalation_evidence_window_id", sa.Integer(), nullable=True))
    op.add_column("alerts", sa.Column("last_notification_error", sa.String(), nullable=True))
    op.add_column(
        "alerts", sa.Column("last_notification_error_at", sa.DateTime(timezone=True), nullable=True)
    )
    # Explicit names -- op.create_foreign_key(None, ...) lets Postgres pick an
    # auto-generated name, which downgrade() then has no reliable way to
    # reference to drop it again (op.drop_constraint requires a real name).
    op.create_foreign_key(
        "fk_alerts_escalation_evidence_baseline_id",
        "alerts",
        "baselines",
        ["escalation_evidence_baseline_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_alerts_escalation_evidence_window_id",
        "alerts",
        "evaluation_windows",
        ["escalation_evidence_window_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_alerts_escalation_evidence_window_id", "alerts", type_="foreignkey")
    op.drop_constraint("fk_alerts_escalation_evidence_baseline_id", "alerts", type_="foreignkey")
    op.drop_column("alerts", "last_notification_error_at")
    op.drop_column("alerts", "last_notification_error")
    op.drop_column("alerts", "escalation_evidence_window_id")
    op.drop_column("alerts", "escalation_evidence_config_hash")
    op.drop_column("alerts", "escalation_evidence_baseline_id")
    op.drop_column("alerts", "escalation_evidence_threshold")
    op.drop_column("alerts", "escalation_evidence_statistic")
    # ### end Alembic commands ###
