"""add alerts table

Revision ID: 30b0e51a0e89
Revises: 02f09ffe3510
Create Date: 2026-07-19 04:48:39.316088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30b0e51a0e89'
down_revision: Union[str, Sequence[str], None] = '02f09ffe3510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('kind', sa.Enum('DRIFT', 'PERFORMANCE', 'NOT_COMPUTABLE', name='alert_kind'), nullable=False),
    sa.Column('signal_name', sa.String(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=True),
    sa.Column('segment_dimension', sa.String(), nullable=True),
    sa.Column('segment_value', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ESCALATED', 'RESOLVED', name='alert_status'), nullable=False),
    sa.Column('consecutive_breaching_windows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('consecutive_clear_windows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('evidence_statistic', sa.Float(), nullable=True),
    sa.Column('evidence_threshold', sa.Float(), nullable=True),
    sa.Column('evidence_baseline_id', sa.Integer(), nullable=True),
    sa.Column('evidence_config_hash', sa.String(), nullable=True),
    sa.Column('evidence_window_id', sa.Integer(), nullable=True),
    sa.Column('evidence_reason', sa.String(), nullable=True),
    sa.Column('first_opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_window_id', sa.Integer(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_notified_status', sa.Enum('OPEN', 'ESCALATED', 'RESOLVED', name='alert_status'), nullable=True),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_aggregate', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('aggregated_signal_count', sa.Integer(), nullable=True),
    sa.Column('aggregated_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['evidence_baseline_id'], ['baselines.id'], ),
    sa.ForeignKeyConstraint(['evidence_window_id'], ['evaluation_windows.id'], ),
    sa.ForeignKeyConstraint(['last_seen_window_id'], ['evaluation_windows.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_model', 'alerts', ['model_id'], unique=False)
    op.create_index('uq_alerts_active_identity', 'alerts', ['model_id', 'kind', 'signal_name', sa.literal_column("COALESCE(feature_name, '')"), sa.literal_column("COALESCE(segment_dimension, '')"), sa.literal_column("COALESCE(segment_value, '')")], unique=True, postgresql_where=sa.text("status != 'RESOLVED' AND NOT is_aggregate"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_alerts_active_identity', table_name='alerts', postgresql_where=sa.text("status != 'RESOLVED' AND NOT is_aggregate"))
    op.drop_index('ix_alerts_model', table_name='alerts')
    op.drop_table('alerts')
    # drop_table does not auto-drop the enum types it implicitly created --
    # they must be dropped explicitly, same lesson learned twice already
    # in this project's migration history.
    sa.Enum(name='alert_kind').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='alert_status').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
