"""initial schema

Revision ID: 3b198f514b4a
Revises: 
Create Date: 2026-07-19 01:07:33.870716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b198f514b4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('first_registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('binning_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_one_active_baseline_per_model', 'baselines', ['model_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prediction_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prediction_score', sa.Float(), nullable=True),
    sa.Column('segment_values', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'prediction_id', name='uq_predictions_model_prediction')
    )
    op.create_index('ix_predictions_model_predicted_at', 'predictions', ['model_id', 'predicted_at'], unique=False)
    op.create_index('ix_predictions_segment_values', 'predictions', ['segment_values'], unique=False, postgresql_using='gin')
    op.create_table('baseline_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baseline_id', sa.Integer(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prediction_score', sa.Float(), nullable=True),
    sa.Column('segment_values', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['baselines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_baseline_records_baseline_id', 'baseline_records', ['baseline_id'], unique=False)
    op.create_table('evaluation_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('baseline_id', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('config_hash', sa.String(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('performance_computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('n_predictions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('n_labels', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['baselines.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'window_start', 'window_end', name='uq_evaluation_windows_model_range')
    )
    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('label_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('labeled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id', 'prediction_id'], ['predictions.model_id', 'predictions.prediction_id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_labels_model_prediction', 'labels', ['model_id', 'prediction_id'], unique=False)
    op.create_table('drift_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_window_id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.Column('segment_dimension', sa.String(), nullable=True),
    sa.Column('segment_value', sa.String(), nullable=True),
    sa.Column('test_method', sa.Enum('PSI', 'KS', 'CHI_SQUARE', 'JSD', name='test_method'), nullable=False),
    sa.Column('statistic', sa.Float(), nullable=False),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('corrected_p_value', sa.Float(), nullable=True),
    sa.Column('is_significant', sa.Boolean(), nullable=False),
    sa.Column('n_baseline', sa.Integer(), nullable=False),
    sa.Column('n_live', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_window_id'], ['evaluation_windows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_drift_results_window', 'drift_results', ['evaluation_window_id'], unique=False)
    op.create_index('ix_drift_results_window_feature', 'drift_results', ['evaluation_window_id', 'feature_name'], unique=False)
    op.create_table('performance_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_window_id', sa.Integer(), nullable=False),
    sa.Column('segment_dimension', sa.String(), nullable=True),
    sa.Column('segment_value', sa.String(), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('n_labeled', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_retroactive', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['evaluation_window_id'], ['evaluation_windows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_performance_results_window', 'performance_results', ['evaluation_window_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_performance_results_window', table_name='performance_results')
    op.drop_table('performance_results')
    op.drop_index('ix_drift_results_window_feature', table_name='drift_results')
    op.drop_index('ix_drift_results_window', table_name='drift_results')
    op.drop_table('drift_results')
    sa.Enum(name='test_method').drop(op.get_bind(), checkfirst=False)
    op.drop_index('ix_labels_model_prediction', table_name='labels')
    op.drop_table('labels')
    op.drop_table('evaluation_windows')
    op.drop_index('ix_baseline_records_baseline_id', table_name='baseline_records')
    op.drop_table('baseline_records')
    op.drop_index('ix_predictions_segment_values', table_name='predictions', postgresql_using='gin')
    op.drop_index('ix_predictions_model_predicted_at', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_one_active_baseline_per_model', table_name='baselines', postgresql_where=sa.text('is_active'))
    op.drop_table('baselines')
    op.drop_table('models')
    # ### end Alembic commands ###
