"""add status and reason to performance_results

Revision ID: 86a7bba431ef
Revises: 4c9bbe9b9ec8
Create Date: 2026-07-19 01:55:03.455131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a7bba431ef'
down_revision: Union[str, Sequence[str], None] = '4c9bbe9b9ec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # add_column() does not auto-create a Postgres enum type the way create_table()
    # does, so it must be created explicitly first.
    metric_status = sa.Enum('COMPUTED', 'NOT_COMPUTABLE', name='metric_status')
    metric_status.create(op.get_bind(), checkfirst=False)
    op.add_column('performance_results', sa.Column('status', metric_status, nullable=False))
    op.add_column('performance_results', sa.Column('not_computable_reason', sa.String(), nullable=True))
    op.alter_column('performance_results', 'metric_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('performance_results', 'metric_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('performance_results', 'not_computable_reason')
    op.drop_column('performance_results', 'status')
    sa.Enum(name='metric_status').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
